language: node_js
matrix:
  fast_finish: true
node_js:
  - 10.13.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 >
    ./codeclimate-test-reporter
  - chmod +x ./codeclimate-test-reporter
  - ./codeclimate-test-reporter before-build
  - npm run build
script:
  - npm run lint
  - npm run test
after_script:
  - ./codeclimate-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
