name: verify

on:
  push:
    branches: [master]
  pull_request_target:

jobs:
  all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 18.x

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          FORCE_COLOR: 3
          TERM: xterm-256color

      - name: Lint
        run: yarn lint
        env:
          FORCE_COLOR: 3
          TERM: xterm-256color

      - name: Test
        run: yarn test
        env:
          FORCE_COLOR: 3
          TERM: xterm-256color
